### PR TITLE
Manage swift object for lb

### PR DESCRIPTION
**Pull request by Polina-Gubina**
Manage swift object for lb

### CODE REVIEW

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by lego963 — DISMISSED** [review]

**Review by lego963 — DISMISSED** [review]

**Comment by Polina-Gubina** [comment]
recheck

**Comment by Polina-Gubina** [comment]
recheck

**Review by lego963 — APPROVED** [review]

**Review by anton-sidelnikov — APPROVED** [review]

**Review by irina-pereiaslavskaia — APPROVED** [review]

**Comment by lego963** [comment]
recheck

**Comment by Polina-Gubina** [comment]
recheck

**Pull request merged**
