### PR TITLE
Add acceptance tests for monitoring infrastructure building

### PR DESCRIPTION
**Pull request by outcatcher**
Run `setup` and `destroy` playbooks for each scenario with the new filename format `*_monitoring_*.yaml`.

Move `terraform_workspace` var to inventory.

Additionally, refer to #334 

This PR contains other changes merged into this branch:
- #341
- #338
- #343 (?)

### CODE REVIEW

**Comment by outcatcher** [comment]
recheck

**Review by lego963 — DISMISSED** [review]

**Review by Polina-Gubina — DISMISSED** [review]

**Review by Polina-Gubina — DISMISSED** [review]

**Comment by outcatcher** [comment]
recheck

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by lego963 — DISMISSED** [review]

**Review by Polina-Gubina — DISMISSED** [review]

**Comment by outcatcher** [comment]
recheck-post

**Review by Polina-Gubina — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Comment by outcatcher** [comment]
recheck

**Review by lego963 — DISMISSED** [review]

**Review by Polina-Gubina — DISMISSED** [review]

**Review by lego963 — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by Polina-Gubina — DISMISSED** [review]

**Review by anton-sidelnikov — APPROVED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Comment by outcatcher** [comment]
recheck

**Review by Polina-Gubina — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by Polina-Gubina — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by lego963 — DISMISSED** [review]

**Review by Polina-Gubina — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by anton-sidelnikov — DISMISSED** [review]

**Review by Polina-Gubina — DISMISSED** [review]

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Comment by outcatcher** [comment]
recheck

**Pull request closed without merging**
